name: Run MEV Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install web3 numpy scikit-learn requests pandas

      - name: Run MEV Bot
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETH_RPC: ${{ secrets.ETH_RPC }}
          BSC_RPC: ${{ secrets.BSC_RPC }}
          AVAX_RPC: ${{ secrets.AVAX_RPC }}
          SOL_RPC: ${{ secrets.SOL_RPC }}
          ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
        run: python mev_bot.py
      - name: Email Notifications
        if: always()
        run: |
          if grep -q "Trade Executed" alerts.txt; then
            echo "Trade executed successfully!" | mail -s "MEV Bot Alert" erebusxx2@gmail.com
          fi
