name: Run MEV Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y web3 && pip install --no-cache-dir web3 numpy scikit-learn requests pandas python-dotenv
          pip list  # ✅ Show installed packages for debugging

      - name: Run MEV Bot
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETH_RPC: ${{ secrets.ETH_RPC }}
          FLASH_LOAN_CONTRACT: ${{ secrets.FLASH_LOAN_CONTRACT }}
        run: |
          set -o pipefail
          python mev_bot.py 2>&1 | tee mev_debug.log || echo "❌ MEV Bot crashed. Check mev_debug.log for details."

      - name: Show Debug Log
        run: |
          if [ -f mev_debug.log ]; then
            echo "📢 MEV Debug Log:"
            cat mev_debug.log
          else
            echo "⚠️ No debug log found. The bot may have crashed before logging."
          fi
